project:
  type: website

website:
  title: "Travel"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AngelaMaryThomas
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    css: styles.css



